### ISSUE TITLE
bit.ly link in screenshot in README is broken

### ISSUE THREAD

**Issue by jchannon** [Geri-Borbas/VSCode.Extension.eppz_Code#3] opened 2017-04-17 12:29 UTC
As title suggests 😄

**Comment by Geri-Borbas** [comment] 2017-04-17 18:44
Hey thanks for the spot! 🎯 

I knew right after I published it, but it was intended mainly for Twitter / Screenshot only communication (which has a really low volume at the moment).

I'll fix it when I roll out more screenshots in future updates (ShaderLab / JSON coloring and more).

**Comment by Geri-Borbas** [comment] 2017-04-17 18:46
What was your use case anyway?
Did you try to reach the theme, after you saw it on Twitter?

(I suppose people discover themes from VS Code itself in Extension search)

**Comment by jchannon** [comment] 2017-04-17 18:48
I found it in VS Code marketplace and installed it then saw the bit.ly link :)

**Comment by Geri-Borbas** [comment] 2017-04-19 01:14
Just pushed the fix along with `1.1.0` updates!
See the brand new [**`README.md`**](https://github.com/eppz/VSCode.Extension.eppz_Code/blob/master/README.md)

Thanks again. 👌

**Closed as completed by Geri-Borbas** 2017-04-19 01:14 UTC
